import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout"; // Import client-side layout

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Canna Miami",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap the content inside ClientLayout for client-side logic */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
